joint_limits:
  r_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  r_shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  r_upper_arm_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  r_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1.5
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  r_forearm_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: true
  r_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  r_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: true
  l_shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  l_shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  l_upper_arm_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  l_elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  l_forearm_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: true
  l_wrist_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: false
  l_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 100.0
    has_accleration_limits: false
    max_acceleration: 100.0
    angle_wraparound: true
