## This file should be loaded under <robot description>_collision

default_collision_operations:

    # Right arm
  - object1: r_shoulder_pan_link
    object2: torso_lift_link
    operation: disable

  - object1: r_upper_arm_link
    object2: torso_lift_link
    operation: disable

  - object1: r_upper_arm_link
    object2: r_elbow_flex_link
    operation: disable

  - object1: r_elbow_flex_link
    object2: r_forearm_link
    operation: disable

  - object1: r_forearm_link
    object2: r_gripper_palm_link
    operation: disable

  - object1: torso_lift_link
    object2: r_dummy_forearm_link
    operation: enable

  - object1: torso_lift_link
    object2: r_dummy_forearm_ext_link
    operation: enable

  - object1: base_link
    object2: r_dummy_forearm_link
    operation: enable

  - object1: base_link
    object2: r_dummy_forearm_ext_link
    operation: enable

  - object1: r_shoulder_pan_link
    object2: r_dummy_forearm_link
    operation: enable

  - object1: r_shoulder_pan_link
    object2: r_dummy_forearm_ext_link
    operation: enable

    # Left arm
  - object1: l_shoulder_pan_link
    object2: torso_lift_link
    operation: disable

  - object1: l_upper_arm_link
    object2: torso_lift_link
    operation: disable

  - object1: l_upper_arm_link
    object2: l_elbow_flex_link
    operation: disable

  - object1: l_elbow_flex_link
    object2: l_forearm_link
    operation: disable

  - object1: l_forearm_link
    object2: l_gripper_palm_link
    operation: disable

  - object1: torso_lift_link
    object2: l_dummy_forearm_link
    operation: enable

  - object1: torso_lift_link
    object2: l_dummy_forearm_ext_link
    operation: enable

  - object1: base_link
    object2: l_dummy_forearm_link
    operation: enable

  - object1: base_link
    object2: l_dummy_forearm_ext_link
    operation: enable

  - object1: l_shoulder_pan_link
    object2: l_dummy_forearm_link
    operation: enable

  - object1: l_shoulder_pan_link
    object2: l_dummy_forearm_ext_link
    operation: enable

## The padding for the robot body parts to be considered when collision checking with the environment
robot_padd: 0.00

## The scaling for the robot body parts to be considered when collision checking with the environment
robot_scale: 1.0
