
multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link

groups:
  - name: left_arm
    base_link: torso_lift_link
    tip_link: l_elbow_flex_link

default_robot_padding: .02

default_object_padding: .03

distance_collision_operations:
  # disable for self, non-intra group collisions
  - object1: l_shoulder_pan_link
    object2: l_shoulder_pan_link
    operation: disable

  - object1: l_shoulder_lift_link
    object2: l_shoulder_lift_link
    operation: disable

  - object1: l_upper_arm_roll_link
    object2: l_upper_arm_roll_link
    operation: disable

  # settings for intra_group collisions
  - object1: left_arm
    object2: left_arm
    operation: disable

  - object1: l_shoulder_pan_link
    object2: l_forearm_link
    operation: enable




default_collision_operations:
  - object1: torso_lift_link
    object2: l_shoulder_pan_link
    operation: disable  # Adjacent in collision
  - object1: l_shoulder_pan_link
    object2: l_shoulder_lift_link
    operation: disable  # Adjacent in collision
  - object1: l_shoulder_lift_link
    object2: l_upper_arm_roll_link
    operation: disable  # Adjacent in collision
  - object1: l_upper_arm_roll_link
    object2: l_upper_arm_link
    operation: disable  # Adjacent in collision
  - object1: l_upper_arm_link
    object2: l_elbow_flex_link
    operation: disable  # Adjacent in collision
  - object1: l_shoulder_pan_link
    object2: l_upper_arm_link
    operation: disable  # Default in collision

  - object1: l_upper_arm_link
    object2: l_dummy_forearm_link
    operation: disable  # Default in collision
  - object1: l_elbow_flex_link
    object2: l_forearm_roll_link
    operation: disable  # Default in collision
  - object1: l_elbow_flex_link
    object2: l_dummy_forearm_link
    operation: disable  # Default in collision
  - object1: l_forearm_roll_link
    object2: l_dummy_forearm_ext_link
    operation: disable  # Default in collision
  - object1: l_forearm_roll_link
    object2: l_dummy_forearm_link
    operation: disable  # Default in collision
  - object1: l_dummy_forearm_ext_link
    object2: l_dummy_forearm_link
    operation: disable  # Default in collision
